--liquibase formatted sql

--changeset orion:1
CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    VARCHAR(64) UNIQUE NOT NULL,
    password VARCHAR(80)        NOT NULL
);
--rollback DROP TABLE users

--changeset orion:2
CREATE TABLE IF NOT EXISTS locations
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(64) NOT NULL,
    user_id   BIGINT REFERENCES users (id) ON DELETE CASCADE,
    latitude  DECIMAL     NOT NULL,
    longitude DECIMAL     NOT NULL
);
--rollback DROP TABLE locations

--changeset orion:3
CREATE TABLE IF NOT EXISTS sessions
(
    id         UUID PRIMARY KEY,
    user_id    BIGINT REFERENCES users (id) ON DELETE CASCADE,
    expires_at TIMESTAMP NOT NULL
);
--rollback DROP TABLE sessions